[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
padding.x = 0
padding.y = 0

[font]
size = 22

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[colors.primary]
background = "#000000"
foreground = "#ffffff"
